from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, Boolean, Text, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship
from datetime import datetime

Base = declarative_base()

class TravelBooking(Base):
    """Travel booking with multiple components"""
    __tablename__ = 'travel_bookings'
    
    id = Column(Integer, primary_key=True, index=True)
    booking_reference = Column(String(50), unique=True, index=True)
    customer_name = Column(String(100), nullable=False)
    customer_email = Column(String(100), nullable=False)
    booking_date = Column(DateTime, default=datetime.utcnow)
    travel_date = Column(DateTime, nullable=False)
    destination = Column(String(100), nullable=False)
    origin = Column(String(100), nullable=False)
    total_cost = Column(Float, nullable=False)
    status = Column(String(20), default='active')  # active, cancelled, completed
    
    # Relationships
    components = relationship("BookingComponent", back_populates="booking", cascade="all, delete-orphan")
    refund_estimates = relationship("RefundEstimate", back_populates="booking", cascade="all, delete-orphan")


class BookingComponent(Base):
    """Individual components of a booking (flight, hotel, visa, insurance)"""
    __tablename__ = 'booking_components'
    
    id = Column(Integer, primary_key=True, index=True)
    booking_id = Column(Integer, ForeignKey('travel_bookings.id'), nullable=False)
    component_type = Column(String(20), nullable=False)  # flight, hotel, visa, insurance
    provider_name = Column(String(100), nullable=False)
    cost = Column(Float, nullable=False)
    refund_policy = Column(Text, nullable=True)
    is_refundable = Column(Boolean, default=False)
    cancellation_fee = Column(Float, default=0.0)
    
    # Relationships
    booking = relationship("TravelBooking", back_populates="components")


class RiskEvent(Base):
    """Global risk events (wars, natural disasters, pandemics)"""
    __tablename__ = 'risk_events'
    
    id = Column(Integer, primary_key=True, index=True)
    event_type = Column(String(50), nullable=False)  # war, natural_disaster, pandemic, terrorism
    severity = Column(String(20), nullable=False)  # low, medium, high, critical
    affected_region = Column(String(100), nullable=False)
    start_date = Column(DateTime, nullable=False)
    end_date = Column(DateTime, nullable=True)
    description = Column(Text, nullable=True)
    is_active = Column(Boolean, default=True)


class HistoricalRefund(Base):
    """Historical refund outcomes for training ML models"""
    __tablename__ = 'historical_refunds'
    
    id = Column(Integer, primary_key=True, index=True)
    component_type = Column(String(20), nullable=False)
    provider_name = Column(String(100), nullable=False)
    original_cost = Column(Float, nullable=False)
    refund_amount = Column(Float, nullable=False)
    refund_percentage = Column(Float, nullable=False)
    event_type = Column(String(50), nullable=False)
    event_severity = Column(String(20), nullable=False)
    days_before_travel = Column(Integer, nullable=False)
    was_force_majeure = Column(Boolean, default=False)
    had_insurance = Column(Boolean, default=False)
    refund_date = Column(DateTime, default=datetime.utcnow)
    region = Column(String(100), nullable=False)


class RefundEstimate(Base):
    """Refund estimates generated by the ML model"""
    __tablename__ = 'refund_estimates'
    
    id = Column(Integer, primary_key=True, index=True)
    booking_id = Column(Integer, ForeignKey('travel_bookings.id'), nullable=False)
    estimate_date = Column(DateTime, default=datetime.utcnow)
    
    # Predictions
    expected_refund_amount = Column(Float, nullable=False)
    expected_refund_percentage = Column(Float, nullable=False)
    confidence_lower = Column(Float, nullable=False)  # Lower bound of confidence interval
    confidence_upper = Column(Float, nullable=False)  # Upper bound of confidence interval
    confidence_level = Column(Float, default=0.95)  # 95% confidence interval
    
    # Risk factors
    current_risk_level = Column(String(20), nullable=False)  # low, medium, high, critical
    risk_score = Column(Float, nullable=False)  # 0-100
    
    # Scenario analysis
    best_case_refund = Column(Float, nullable=False)
    worst_case_refund = Column(Float, nullable=False)
    most_likely_refund = Column(Float, nullable=False)
    
    # Model metadata
    model_version = Column(String(20), default='1.0')
    prediction_confidence = Column(Float, nullable=False)  # Model's confidence in prediction
    
    # Relationships
    booking = relationship("TravelBooking", back_populates="refund_estimates")


class ProviderPolicy(Base):
    """Provider refund policies"""
    __tablename__ = 'provider_policies'
    
    id = Column(Integer, primary_key=True, index=True)
    provider_name = Column(String(100), nullable=False, unique=True)
    provider_type = Column(String(20), nullable=False)  # airline, hotel, insurance, visa
    
    # Policy details
    standard_refund_percentage = Column(Float, default=0.0)
    force_majeure_refund_percentage = Column(Float, default=0.0)
    cancellation_fee = Column(Float, default=0.0)
    refund_processing_days = Column(Integer, default=30)
    
    # Policy text
    policy_text = Column(Text, nullable=True)
    force_majeure_clause = Column(Text, nullable=True)
    last_updated = Column(DateTime, default=datetime.utcnow)


# Database setup
DATABASE_URL = "sqlite:///./refund_estimation.db"
engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

def init_db():
    """Initialize database tables"""
    Base.metadata.create_all(bind=engine)

def get_db():
    """Dependency for getting database session"""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

# Made with Bob
